[package]
name = "vdf-parse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winnow = { version = "0.6", features = ["simd"]}
serde = {version = "1.0", features = ["derive"]}

[profile.release]
lto = "fat"
codegen-units = 1
debug = false

[features]
"debug" = ["winnow/debug"]
